### PR TITLE
Troll face

### PR DESCRIPTION
**Pull request by fusionstrings**
@guybedford I guess I am only few months late here :).

### CODE REVIEW

**Comment by guybedford** [comment]
Is this... censorship? :P You can entirely blame @Jarreddebeer for encouraging me to leave this in from the prototype!

**Comment by fusionstrings** [comment]
@guybedford https://discord.com/channels/570400367884501026/570400367884501032/816645856069419018 :)

**Comment by guybedford** [comment]
Ahaha I completely forgot I said that. I should throw flippant comments about suggested changes more often it seems :P

**Comment by Jarreddebeer** [comment]
Probably the most memorable and clicked help button ever.. I take full responsibility :D

**Pull request closed without merging**
