### PR TITLE
(chore): bump @jspm/generators@1.1.10

### PR DESCRIPTION
**Pull request by JayaKrishnaNamburu**

### CODE REVIEW

**Review by guybedford — APPROVED** [review]

**Comment by guybedford** [comment]
Note that the generator version didn't actually bump here, because the import map is acting as a lock file.

**Comment by JayaKrishnaNamburu** [comment]
Ah Good catch, tried it in my very old fork where the generator was like `1.0.2` :D and thought the same would have been now. Will change the `import-map` too with the `cli`. So, the generates maps from the deployed project can take advantage of it too 👍

**Comment by JayaKrishnaNamburu** [comment]
Yup, for now i am using `cli` to manually bump the `import-map` inside `sandbox.html` file. Will create a separate issue to adopt the `cli` for the project 👍. Waiting for the [build](https://api.jspm.io/build/@jspm/generator@1.1.10) to pass for the `cdn`

**Comment by guybedford** [comment]
@JayaKrishnaNamburu is the CLI bumping the generator version or no? Did you try `jspm update`?

**Comment by JayaKrishnaNamburu** [comment]
There are few observations here

- `jspm update` seems to check for only `imports` and not `scopes`. And the repo is using `@jspm/generator` under scopes. https://github.com/jspm/generator.jspm.io/blob/main/sandbox.html#L36
- The build for `@jspm/generator@1.1.10` seems to be stuck or failed or something. It is in the same status https://api.jspm.io/build/@jspm/generator@1.1.10

**Comment by guybedford** [comment]
@JayaKrishnaNamburu the build server is a little backlogged at the moment, hopefully our new server will be up in the next month to alleviate the load. I've triggered the build for the generator, it should be available now.

`jspm update` checking only for imports seems correct to me. Perhaps we should reevaluate the import map here using the CLI so that it has the generator in imports?

**Comment by JayaKrishnaNamburu** [comment]
> jspm update checking only for imports seems correct to me. Perhaps we should reevaluate the import map here using the CLI so that it has the generator in imports?

Yup, exactly when the project is going to adopt the `cli` by dropping the current way of import-maps generation using `chomp` task. We should change the map a little 👍

**Pull request merged**
